### ISSUE TITLE
Error happen in caliper logs

### ISSUE THREAD

**Issue by CShiru** [adhavpavan/ContainerisingCaliperForFabricBenchmark#1]
2021.02.27-12:35:07.434 info  [caliper] [message-handler] 	Handling "prepare" message
2021.02.27-12:35:07.441 error [caliper] [message-handler] 	Handled unsuccessful "prepare" message for worker 0 and test round 0 with error Error: Cannot find module 'uuid'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/hyperledger/caliper/workspace/benchmarks/scenario/simple/pavan/open.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by adhavpavan** [comment]
Please run npm install in local caliper repo

**Comment by anishajain22** [comment]
I tried npm install. No luck:/

**Comment by CShiru** [comment]
I tried npm install in docker and solved the problem successfully
